# Use from https://gist.github.com/vidavidorra/548ffbcdae99d752da02


# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      
# Build your code e.g. by calling make
script:
  - doxygen
  
# Blacklist
branches:
  except:
    - gh-pages
    
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  on:
    branch: develop # we build only when develop updates but not other branch

notifications:
  email: false
