var annotated =
[
    [ "AbstractCar", "class_abstract_car.html", "class_abstract_car" ],
    [ "AbstractCarPosition", "class_abstract_car_position.html", "class_abstract_car_position" ],
    [ "CarTrafficManager", "class_car_traffic_manager.html", "class_car_traffic_manager" ],
    [ "GameModeController", "class_game_mode_controller.html", "class_game_mode_controller" ],
    [ "GlobalLayers", "class_global_layers.html", null ],
    [ "GlobalTags", "class_global_tags.html", null ],
    [ "Intersection", "class_intersection.html", "class_intersection" ],
    [ "IntersectionBuilder", "class_intersection_builder.html", "class_intersection_builder" ],
    [ "IntersectionCustomization", "class_intersection_customization.html", "class_intersection_customization" ],
    [ "IntersectionCustomizationBuilder", "class_intersection_customization_builder.html", "class_intersection_customization_builder" ],
    [ "IntersectionManager", "class_intersection_manager.html", "class_intersection_manager" ],
    [ "IntersectionMath", "class_intersection_math.html", null ],
    [ "IntersectionTrafficControl", "class_intersection_traffic_control.html", "class_intersection_traffic_control" ],
    [ "IntersectionTrafficMath", "class_intersection_traffic_math.html", "class_intersection_traffic_math" ],
    [ "MapGeneractionController", "class_map_generaction_controller.html", "class_map_generaction_controller" ],
    [ "Math3d", "class_math3d.html", null ],
    [ "MouseCollisionDetection", "class_mouse_collision_detection.html", null ],
    [ "NavigationManager", "class_navigation_manager.html", "class_navigation_manager" ],
    [ "Road", "class_road.html", "class_road" ],
    [ "RoadAdjustmentController", "class_road_adjustment_controller.html", null ],
    [ "RoadBuilder", "class_road_builder.html", "class_road_builder" ],
    [ "RoadConfiguration", "class_road_configuration.html", "class_road_configuration" ],
    [ "RoadConstructionController", "class_road_construction_controller.html", "class_road_construction_controller" ],
    [ "RoadTrafficControl", "class_road_traffic_control.html", "class_road_traffic_control" ],
    [ "TrafficAdditionController", "class_traffic_addition_controller.html", "class_traffic_addition_controller" ],
    [ "TrafficLightControl", "class_traffic_light_control.html", "class_traffic_light_control" ],
    [ "TruckControl", "class_truck_control.html", "class_truck_control" ]
];